# Generated by Django 3.1.1 on 2020-09-24 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=256)),
                ('auctionwatchlist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionwatchlist', to='auctions.auction')),
                ('userwatchlist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userwatchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=256)),
                ('auctionbid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionbid', to='auctions.auction')),
                ('userbid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('comments', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('auctioncomments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctioncomments', to='auctions.auction')),
                ('usercomments', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercomments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
