# Generated by Django 3.1.1 on 2020-09-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200924_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bidby', models.CharField(max_length=256)),
                ('notes', models.CharField(max_length=256)),
                ('auctionbid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionbid', to='auctions.auction')),
            ],
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
