# Generated by Django 3.1.1 on 2020-09-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200924_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctioncomment',
            name='usercomments',
        ),
        migrations.RemoveField(
            model_name='bidauction',
            name='bidby',
        ),
        migrations.RemoveField(
            model_name='auctioncomment',
            name='auctioncomments',
        ),
        migrations.AddField(
            model_name='auctioncomment',
            name='auctioncomments',
            field=models.ManyToManyField(blank=True, related_name='auctioncomments', to='auctions.Auction'),
        ),
        migrations.RemoveField(
            model_name='bidauction',
            name='auctionbid',
        ),
        migrations.AddField(
            model_name='bidauction',
            name='auctionbid',
            field=models.ManyToManyField(blank=True, related_name='auctionbid', to='auctions.Auction'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='auctionwatchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auctionwatchlist',
            field=models.ManyToManyField(blank=True, related_name='auctionwatchlist', to='auctions.Auction'),
        ),
    ]
