# Generated by Django 3.1.1 on 2020-09-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200925_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='userwatchlist',
        ),
    ]
