# Generated by Django 3.1.1 on 2020-09-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200925_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctioncomment',
            old_name='auctioncomments',
            new_name='auction',
        ),
        migrations.RemoveField(
            model_name='bidauction',
            name='auctionbid',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='auctionwatchlist',
        ),
        migrations.AddField(
            model_name='bidauction',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='bidauctions', to='auctions.Auction'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='watchlists', to='auctions.Auction'),
        ),
    ]
