# Generated by Django 3.1.1 on 2020-09-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20200925_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctioncomment',
            old_name='auction',
            new_name='auctions',
        ),
        migrations.RenameField(
            model_name='bidauction',
            old_name='auction',
            new_name='auctions',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='auction',
            new_name='auctions',
        ),
    ]
