# Generated by Django 3.1.1 on 2020-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200925_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctioncomment',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='auctionsc', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='bidauction',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='auctions', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='auctionsw', to='auctions.Auction'),
        ),
    ]
