# Generated by Django 3.1.1 on 2020-09-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200926_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=256, null=True)),
                ('auctions', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionsb', to='auctions.auction')),
                ('users', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BidAuction',
        ),
    ]
