# Generated by Django 3.1.1 on 2020-09-26 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200926_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.FloatField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('notes', models.CharField(max_length=256, null=True)),
                ('auctionedby', models.CharField(max_length=256, null=True)),
                ('auctionbid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctionbid', to='auctions.auction')),
            ],
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
