# Generated by Django 3.1.1 on 2020-09-28 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_comments_userc'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='userw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userw', to=settings.AUTH_USER_MODEL),
        ),
    ]
