# Generated by Django 3.1.1 on 2020-10-01 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist_userw'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='userb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userb', to=settings.AUTH_USER_MODEL),
        ),
    ]
